version: '3.8'
services:

  rabbitmq:
    image: rabbitmq:3.12.12-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq
  
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pix-dotnet-dockerized
    ports:
      - 5433:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  pix:
    image: pix
    container_name: pix
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - DATABASE__HOST=postgres
      - DATABASE__PORT=5432
      - DATABASE__USERNAME=postgres
      - DATABASE__PASSWORD=postgres
      - DATABASE__NAME=pix-dotnet-dockerized

  migrate:
    image: pix-migrate
    container_name: migrate
    build:
      context: .
      dockerfile: Dockerfile.migrations
    environment:
      - DATABASE__HOST=postgres
      - DATABASE__PORT=5432
      - DATABASE__USERNAME=postgres
      - DATABASE__PASSWORD=postgres
      - DATABASE__NAME=pix-dotnet-dockerized

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pdrocha03@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=151099
    ports:
      - "16543:80"
    depends_on:
      - postgres

volumes:
  postgres-volume:
  rabbitmq-volume: