version: '3.8'
services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    pid: host
    network_mode: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    network_mode: host
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    network_mode: host
    environment:
      - DATA_SOURCE_URI=localhost:5432/pix-dotnet?sslmode=disable
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASS=151099

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    network_mode: host
    volumes:
      - grafana:/var/lib/grafana

volumes:
  grafana: