version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.12.12-management
    network_mode: host
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq
volumes:
  rabbitmq-volume:
